package view;

import javax.swing.*;
import java.awt.event.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import koneksi.DatabaseConnection;

/**
 * Form Data Buku - Aplikasi Penjualan Buku
 * @author Fadillah
 */
public class BukuFrame extends javax.swing.JFrame {

    private DefaultTableModel model;

    public BukuFrame() {
        initComponents();
        setTitle("Form Data Buku");
        setLocationRelativeTo(null);
        tampilData();

        // Buat model tabel
        model = (DefaultTableModel) tblBuku.getModel();

        // Aksi tombol
        btnSimpan.addActionListener(e -> simpanData());
        btnUbah.addActionListener(e -> ubahData());
        btnHapus.addActionListener(e -> hapusData());
        btnReset.addActionListener(e -> resetForm());
        btnKeluar.addActionListener(e -> dispose());

        // Aksi klik tabel → isi form
        tblBuku.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                int baris = tblBuku.getSelectedRow();
                if (baris >= 0) {
                    txtIdBuku.setText(model.getValueAt(baris, 0).toString());
                    txtJudul.setText(model.getValueAt(baris, 1).toString());
                    txtPengarang.setText(model.getValueAt(baris, 2).toString());
                    txtPenerbit.setText(model.getValueAt(baris, 3).toString());
                    txtHarga.setText(model.getValueAt(baris, 4).toString());
                    txtStok.setText(model.getValueAt(baris, 5).toString());
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlUtama = new javax.swing.JPanel();
        lblJudulAtas = new javax.swing.JLabel();
        txtIdBuku = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        lblJudul = new javax.swing.JLabel();
        txtPengarang = new javax.swing.JTextField();
        lblPengarang = new javax.swing.JLabel();
        txtPenerbit = new javax.swing.JTextField();
        lblPenerbit = new javax.swing.JLabel();
        txtHarga = new javax.swing.JTextField();
        lblHarga = new javax.swing.JLabel();
        txtStok = new javax.swing.JTextField();
        lblStok = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlBawah = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        btnKeluar = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUtama.setBackground(new java.awt.Color(230, 210, 250));

        lblJudulAtas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudulAtas.setText("FORM DATA BUKU");

        txtIdBuku.setEditable(false);

        lblID.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblID.setText("ID Buku :");

        lblJudul.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblJudul.setText("Judul :");

        lblPengarang.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPengarang.setText("Pengarang :");

        lblPenerbit.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblPenerbit.setText("Penerbit :");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblHarga.setText("Harga :");

        lblStok.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        lblStok.setText("Stok :");

        btnSimpan.setBackground(new java.awt.Color(0, 153, 51));
        btnSimpan.setForeground(new java.awt.Color(200, 235, 230));
        btnSimpan.setText("Simpan");

        btnUbah.setText("Ubah");
        btnUbah.setToolTipText("");

        btnHapus.setBackground(new java.awt.Color(204, 0, 0));
        btnHapus.setForeground(new java.awt.Color(200, 235, 230));
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnReset.setText("Reset");

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(lblJudulAtas))
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUtamaLayout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblID)
                                    .addComponent(lblJudul))
                                .addGap(33, 33, 33))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblPenerbit)
                                            .addComponent(lblHarga)
                                            .addComponent(lblStok))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                                        .addComponent(lblPengarang)
                                        .addGap(18, 18, 18)))))
                        .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addComponent(lblJudulAtas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdBuku, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPengarang, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPenerbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStok))
                .addGap(18, 18, 18)
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(35, 35, 35))
        );

        getContentPane().add(pnlUtama, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 290));

        pnlBawah.setBackground(new java.awt.Color(230, 210, 250));

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul", "Pengarang", "Penerbit", "Harga", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tblBuku);

        btnKeluar.setBackground(new java.awt.Color(204, 0, 0));
        btnKeluar.setForeground(new java.awt.Color(200, 235, 230));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBawahLayout = new javax.swing.GroupLayout(pnlBawah);
        pnlBawah.setLayout(pnlBawahLayout);
        pnlBawahLayout.setHorizontalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBawahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBawahLayout.setVerticalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBawahLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKeluar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 510, 210));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        btnKeluar.addActionListener(e -> dispose());
    }//GEN-LAST:event_btnKeluarActionPerformed

// === CRUD FUNGSI ===
    private void tampilData() {
        DefaultTableModel model = (DefaultTableModel) tblBuku.getModel();
        model.setRowCount(0);
        try (Connection conn = DatabaseConnection.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT * FROM buku")) {
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id_buku"),
                    rs.getString("judul"),
                    rs.getString("pengarang"),
                    rs.getString("penerbit"),
                    rs.getDouble("harga"),
                    rs.getInt("stok")
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
        }
    }

    private void simpanData() {
    try (Connection conn = DatabaseConnection.getConnection()) {
        String sql = "INSERT INTO buku (judul, pengarang, penerbit, harga, stok) VALUES (?, ?, ?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

        pst.setString(1, txtJudul.getText());
        pst.setString(2, txtPengarang.getText());
        pst.setString(3, txtPenerbit.getText());
        pst.setDouble(4, Double.parseDouble(txtHarga.getText()));
        pst.setInt(5, Integer.parseInt(txtStok.getText()));

        pst.executeUpdate();

        // ✅ Ambil ID otomatis yang baru dibuat
        ResultSet rs = pst.getGeneratedKeys();
        if (rs.next()) {
            int newId = rs.getInt(1);
            txtIdBuku.setText(String.valueOf(newId)); // tampilkan ID di form
        }

        tampilData();
        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan data: " + e.getMessage());
    }
}


    private void ubahData() {
        if (txtIdBuku.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin diubah!");
            return;
        }
        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "UPDATE buku SET judul=?, pengarang=?, penerbit=?, harga=?, stok=? WHERE id_buku=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtJudul.getText());
            pst.setString(2, txtPengarang.getText());
            pst.setString(3, txtPenerbit.getText());
            pst.setDouble(4, Double.parseDouble(txtHarga.getText()));
            pst.setInt(5, Integer.parseInt(txtStok.getText()));
            pst.setInt(6, Integer.parseInt(txtIdBuku.getText()));
            pst.executeUpdate();
            tampilData();
            resetForm();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ubah data: " + e.getMessage());
        }
    }

    private void hapusData() {
        if (txtIdBuku.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!");
            return;
        }
        try (Connection conn = DatabaseConnection.getConnection()) {
            String sql = "DELETE FROM buku WHERE id_buku=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(txtIdBuku.getText()));
            pst.executeUpdate();
            tampilData();
            resetForm();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus data: " + e.getMessage());
        }
    }

    private void resetForm() {
        txtIdBuku.setText("");
        txtJudul.setText("");
        txtPengarang.setText("");
        txtPenerbit.setText("");
        txtHarga.setText("");
        txtStok.setText("");
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new BukuFrame().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJudulAtas;
    private javax.swing.JLabel lblPenerbit;
    private javax.swing.JLabel lblPengarang;
    private javax.swing.JLabel lblStok;
    private javax.swing.JPanel pnlBawah;
    private javax.swing.JPanel pnlUtama;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtPengarang;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables
}
