package view;

import javax.swing.*;
import java.awt.event.*;
import koneksi.DatabaseConnection;

public class MenuUtama extends javax.swing.JFrame {

    public MenuUtama() {
        initComponents();
        setTitle("Menu Utama Aplikasi Penjualan Buku");
        setLocationRelativeTo(null);

        jMenuItem1.addActionListener(e -> new BukuFrame().setVisible(true));
        jMenuItem2.addActionListener(e -> new PelangganFrame().setVisible(true));
        jMenuItem3.addActionListener(e -> new PenjualanFrame().setVisible(true));
        jMenuItem5.addActionListener(e -> new LaporanFrame().setVisible(true));
        jMenu4.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                System.exit(0);
            }
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUtama = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        lblFooter = new javax.swing.JLabel();
        lblSubJudul = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUtama.setBackground(new java.awt.Color(190, 245, 225));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblJudul.setText("APLIKASI PENJUALAN BUKU");

        lblFooter.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(0, 70, 200));
        lblFooter.setText("Dibuat oleh: Fadillah Fikrie | 2310010211");

        lblSubJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblSubJudul.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSubJudul.setText("Sistem Informasi Penjualan Buku dengan Java dan MySQL Database ");
        lblSubJudul.setToolTipText("");

        javax.swing.GroupLayout pnlUtamaLayout = new javax.swing.GroupLayout(pnlUtama);
        pnlUtama.setLayout(pnlUtamaLayout);
        pnlUtamaLayout.setHorizontalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUtamaLayout.createSequentialGroup()
                        .addComponent(lblSubJudul)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblJudul)
                        .addGap(82, 82, 82))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblFooter)
                .addGap(66, 66, 66))
        );
        pnlUtamaLayout.setVerticalGroup(
            pnlUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUtamaLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(lblJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSubJudul)
                .addGap(33, 33, 33)
                .addComponent(lblFooter)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jMenu1.setText("Master Data");

        jMenuItem1.setText("Buku");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Pelanggan");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItem3.setText("Penjualan");
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Laporan");

        jMenuItem5.setText("Laporan Penjualan");
        jMenu3.add(jMenuItem5);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Keluar");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 // === EVENT HANDLER ===

    // Buka form Buku
    private void menuBukuActionPerformed(java.awt.event.ActionEvent evt) {                                          
        new BukuFrame().setVisible(true);
    }                                         

    // Buka form Pelanggan
    private void menuPelangganActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new PelangganFrame().setVisible(true);
    }                                             

    // Buka form Penjualan
    private void menuPenjualanActionPerformed(java.awt.event.ActionEvent evt) {                                              
        new PenjualanFrame().setVisible(true);
    }                                             

    // Buka form Laporan Buku
    private void menuLaporanBukuActionPerformed(java.awt.event.ActionEvent evt) {                                                
        new LaporanFrame().setVisible(true);
    }                                               

    // Buka form Laporan Penjualan
    private void menuLaporanPenjualanActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        new LaporanFrame().setVisible(true);
    }                                                    

    // Menu keluar
    private void jMenu4MenuSelected(javax.swing.event.MenuEvent evt) {                                    
        int konfirmasi = javax.swing.JOptionPane.showConfirmDialog(
                this, 
                "Apakah Anda yakin ingin keluar?", 
                "Konfirmasi Keluar", 
                javax.swing.JOptionPane.YES_NO_OPTION
        );
        if (konfirmasi == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }                                   

    // Main method
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblSubJudul;
    private javax.swing.JPanel pnlUtama;
    // End of variables declaration//GEN-END:variables
}
