package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import koneksi.DatabaseConnection;

/**
 * Form Data Pelanggan - Aplikasi Penjualan Buku
 * @author Fadillah
 */
public class PelangganFrame extends javax.swing.JFrame {

    DefaultTableModel model;

    public PelangganFrame() {
        initComponents();
        setTitle("Form Data Pelanggan");
        setLocationRelativeTo(null);

        model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID Pelanggan", "Nama", "Alamat", "Telepon"});
        tblPelanggan.setModel(model);

        // === Event Tombol ===
        btnSimpan.addActionListener(e -> simpanData());
        btnUbah.addActionListener(e -> ubahData());
        btnHapus.addActionListener(e -> hapusData());
        btnReset.addActionListener(e -> resetForm());
        btnKeluar.addActionListener(e -> dispose());

        tampilData(); // tampilkan data saat form dibuka
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlAtas = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        pnlTengah = new javax.swing.JPanel();
        lblIdPelanggan = new javax.swing.JLabel();
        lblNama = new javax.swing.JLabel();
        lblAlamat = new javax.swing.JLabel();
        lblTelp = new javax.swing.JLabel();
        txtIdPelanggan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        txtTelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        pnlBawah = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        lblTabel = new javax.swing.JLabel();
        btnKeluar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAtas.setBackground(new java.awt.Color(240, 210, 220));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblJudul.setText("FORM DATA PELANGGAN");

        javax.swing.GroupLayout pnlAtasLayout = new javax.swing.GroupLayout(pnlAtas);
        pnlAtas.setLayout(pnlAtasLayout);
        pnlAtasLayout.setHorizontalGroup(
            pnlAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(153, 153, 153))
        );
        pnlAtasLayout.setVerticalGroup(
            pnlAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAtasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblJudul)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTengah.setBackground(new java.awt.Color(230, 210, 250));

        lblIdPelanggan.setText("ID Pelanggan :");

        lblNama.setText("Nama :");

        lblAlamat.setText("Alamat :");

        lblTelp.setText("Telepon :");

        txtIdPelanggan.setEditable(false);

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane1.setViewportView(txtAlamat);

        btnSimpan.setBackground(new java.awt.Color(0, 153, 51));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(200, 235, 230));
        btnSimpan.setText("Simpan");

        btnUbah.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnUbah.setText("Ubah");

        btnHapus.setBackground(new java.awt.Color(204, 0, 0));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(200, 235, 230));
        btnHapus.setText("Hapus");

        btnReset.setBackground(new java.awt.Color(204, 0, 0));
        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnReset.setForeground(new java.awt.Color(200, 235, 230));
        btnReset.setText("Reset");

        javax.swing.GroupLayout pnlTengahLayout = new javax.swing.GroupLayout(pnlTengah);
        pnlTengah.setLayout(pnlTengahLayout);
        pnlTengahLayout.setHorizontalGroup(
            pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTengahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTengahLayout.createSequentialGroup()
                        .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlTengahLayout.createSequentialGroup()
                                .addComponent(lblIdPelanggan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlTengahLayout.createSequentialGroup()
                                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNama)
                                    .addComponent(lblAlamat)
                                    .addComponent(lblTelp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                                    .addComponent(txtNama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelepon))))
                        .addGap(275, 275, 275))
                    .addGroup(pnlTengahLayout.createSequentialGroup()
                        .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        pnlTengahLayout.setVerticalGroup(
            pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTengahLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdPelanggan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNama))
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTengahLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblAlamat))
                    .addGroup(pnlTengahLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelepon, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(lblTelp))
                .addGap(18, 18, 18)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(21, 21, 21))
        );

        pnlBawah.setBackground(new java.awt.Color(230, 210, 250));

        tblPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nama", "Alamat", "Telepon"
            }
        ));
        jScrollPane3.setViewportView(tblPelanggan);

        lblTabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTabel.setText("TABEL DATA PELANGGAN");

        btnKeluar.setBackground(new java.awt.Color(204, 0, 0));
        btnKeluar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnKeluar.setForeground(new java.awt.Color(200, 235, 230));
        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBawahLayout = new javax.swing.GroupLayout(pnlBawah);
        pnlBawah.setLayout(pnlBawahLayout);
        pnlBawahLayout.setHorizontalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBawahLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBawahLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlBawahLayout.setVerticalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBawahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblTabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(btnKeluar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTengah, javax.swing.GroupLayout.PREFERRED_SIZE, 488, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        btnKeluar.addActionListener(e -> dispose());
    }//GEN-LAST:event_btnKeluarActionPerformed

    // === CRUD ===
    private void tampilData() {
    // Pastikan model sudah terhubung ke tabel
    if (tblPelanggan.getModel() instanceof DefaultTableModel) {
        model = (DefaultTableModel) tblPelanggan.getModel();
    } else {
        model = new DefaultTableModel(new String[]{"ID", "Nama", "Alamat", "Telepon"}, 0);
        tblPelanggan.setModel(model);
    }

    // Kosongkan isi tabel sebelum menambahkan data baru
    model.setRowCount(0);

    try (Connection conn = DatabaseConnection.getConnection();
         Statement st = conn.createStatement();
         ResultSet rs = st.executeQuery("SELECT * FROM pelanggan")) {

        while (rs.next()) {
            model.addRow(new Object[]{
                rs.getInt("id_pelanggan"),
                rs.getString("nama"),
                rs.getString("alamat"),
                rs.getString("telepon")
            });
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal tampil data: " + e.getMessage());
    }
}


    private void simpanData() {
    try (Connection conn = DatabaseConnection.getConnection()) {
        String sql = "INSERT INTO pelanggan (nama, alamat, telepon) VALUES (?, ?, ?)";
        PreparedStatement pst = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);

        pst.setString(1, txtNama.getText());
        pst.setString(2, txtAlamat.getText());
        pst.setString(3, txtTelepon.getText());

        pst.executeUpdate();

        // ✅ Ambil ID otomatis dari database
        ResultSet rs = pst.getGeneratedKeys();
        if (rs.next()) {
            int newId = rs.getInt(1);
            txtIdPelanggan.setText(String.valueOf(newId)); // tampilkan ID di field
        }

        // ✅ Refresh tabel agar langsung menampilkan data baru
        tampilData();

        // ✅ Reset form (kecuali ID)
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");

        JOptionPane.showMessageDialog(this, "Data pelanggan berhasil disimpan!");
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Gagal simpan data: " + e.getMessage());
    }
}



    private void ubahData() {
    int row = tblPelanggan.getSelectedRow();
    if (row >= 0) {
        try (Connection conn = DatabaseConnection.getConnection()) {
            int id = (int) tblPelanggan.getValueAt(row, 0); // ambil ID dari tabel
            String sql = "UPDATE pelanggan SET nama=?, alamat=?, telepon=? WHERE id_pelanggan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, txtNama.getText());
            pst.setString(2, txtAlamat.getText());
            pst.setString(3, txtTelepon.getText());
            pst.setInt(4, id);
            pst.executeUpdate();
            tampilData();
            resetForm();
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal ubah data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin diubah!");
    }
}

    private void hapusData() {
    int row = tblPelanggan.getSelectedRow();
    if (row >= 0) {
        try (Connection conn = DatabaseConnection.getConnection()) {
            // ambil ID dari tabel, kolom pertama
            int id = (int) tblPelanggan.getValueAt(row, 0);
            String sql = "DELETE FROM pelanggan WHERE id_pelanggan=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, id);
            pst.executeUpdate();
            tampilData();
            resetForm();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal hapus data: " + e.getMessage());
        }
    } else {
        JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus!");
    }
}


    private void resetForm() {
        txtIdPelanggan.setText("");
        txtNama.setText("");
        txtAlamat.setText("");
        txtTelepon.setText("");
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new PelangganFrame().setVisible(true));
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAlamat;
    private javax.swing.JLabel lblIdPelanggan;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblTabel;
    private javax.swing.JLabel lblTelp;
    private javax.swing.JPanel pnlAtas;
    private javax.swing.JPanel pnlBawah;
    private javax.swing.JPanel pnlTengah;
    private javax.swing.JTable tblPelanggan;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtIdPelanggan;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTelepon;
    // End of variables declaration//GEN-END:variables
}
