package view;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.util.HashMap;
import koneksi.DatabaseConnection;

/**
 * Form Transaksi Penjualan Buku - Terhubung Database MySQL
 * @author Fadillah
 */
public class PenjualanFrame extends javax.swing.JFrame {

    DefaultTableModel model;
    HashMap<String, Integer> mapBuku = new HashMap<>();
    HashMap<String, Integer> mapPelanggan = new HashMap<>();

    public PenjualanFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Form Transaksi Penjualan Buku");

        // === Buat model tabel ===
        model = new DefaultTableModel(
                new Object[][]{},
                new String[]{"ID Buku", "Judul Buku", "Harga", "Jumlah", "Sub Total"});
        tblPenjualan.setModel(model);

        // === Muat data dari database ===
        loadComboBuku();
        loadComboPelanggan();

        // === Event tombol ===
        btnTambah.addActionListener(e -> tambahBuku());
        btnHapus.addActionListener(e -> hapusBaris());
        btnReset.addActionListener(e -> resetForm());
        btnKeluar.addActionListener(e -> dispose());
        btnSimpan.addActionListener(e -> simpanTransaksi());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAtas = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        pnlTengah = new javax.swing.JPanel();
        lblIdPenjualan = new javax.swing.JLabel();
        lblTanggal = new javax.swing.JLabel();
        lblPelanggan = new javax.swing.JLabel();
        lblBuku = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        txtIdPenjualan = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtJumlah = new javax.swing.JTextField();
        cmbPelanggan = new javax.swing.JComboBox<>();
        cmbBuku = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        pnlBawah = new javax.swing.JPanel();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPenjualan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAtas.setBackground(new java.awt.Color(230, 210, 250));

        lblJudul.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblJudul.setText("Form Transaksi Penjualan Buku");

        javax.swing.GroupLayout pnlAtasLayout = new javax.swing.GroupLayout(pnlAtas);
        pnlAtas.setLayout(pnlAtasLayout);
        pnlAtasLayout.setHorizontalGroup(
            pnlAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(132, 132, 132))
        );
        pnlAtasLayout.setVerticalGroup(
            pnlAtasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAtasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addContainerGap())
        );

        pnlTengah.setBackground(new java.awt.Color(230, 210, 250));

        lblIdPenjualan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblIdPenjualan.setText("ID Penjualan :");

        lblTanggal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTanggal.setText("Tanggal :");

        lblPelanggan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblPelanggan.setText("Pelanggan :");

        lblBuku.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblBuku.setText("Buku :");

        lblJumlah.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblJumlah.setText("Jumlah :");

        txtTanggal.setText("YYYY-MM-DD");

        cmbPelanggan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pelanggan" }));

        cmbBuku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Buku" }));

        btnTambah.setBackground(new java.awt.Color(128, 128, 128));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("Tambah Buku");

        javax.swing.GroupLayout pnlTengahLayout = new javax.swing.GroupLayout(pnlTengah);
        pnlTengah.setLayout(pnlTengahLayout);
        pnlTengahLayout.setHorizontalGroup(
            pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTengahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdPenjualan)
                    .addComponent(lblTanggal)
                    .addComponent(lblBuku)
                    .addComponent(lblJumlah)
                    .addComponent(lblPelanggan))
                .addGap(18, 18, 18)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlTengahLayout.createSequentialGroup()
                        .addComponent(cmbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btnTambah))
                    .addComponent(txtIdPenjualan, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(txtTanggal)
                    .addComponent(txtJumlah))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTengahLayout.setVerticalGroup(
            pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTengahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdPenjualan)
                    .addComponent(txtIdPenjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTanggal)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPelanggan))
                .addGap(18, 18, 18)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuku)
                    .addComponent(cmbBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addGap(15, 15, 15)
                .addGroup(pnlTengahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlBawah.setBackground(new java.awt.Color(230, 210, 250));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTotal.setText("Total :");

        txtTotal.setEditable(false);
        txtTotal.setBackground(new java.awt.Color(190, 224, 240));
        txtTotal.setToolTipText("");

        btnSimpan.setBackground(new java.awt.Color(70, 220, 100));
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan Transaksi");

        btnHapus.setBackground(new java.awt.Color(255, 0, 0));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus Item");

        btnReset.setBackground(new java.awt.Color(128, 128, 128));
        btnReset.setForeground(new java.awt.Color(255, 255, 255));
        btnReset.setText("Reset");

        btnKeluar.setBackground(new java.awt.Color(128, 128, 128));
        btnKeluar.setForeground(new java.awt.Color(255, 255, 255));
        btnKeluar.setText("Keluar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jLabel1.setText("Tabel Penjualan");

        tblPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Harga", "Jumlah", "Sub Total"
            }
        ));
        jScrollPane1.setViewportView(tblPenjualan);

        javax.swing.GroupLayout pnlBawahLayout = new javax.swing.GroupLayout(pnlBawah);
        pnlBawah.setLayout(pnlBawahLayout);
        pnlBawahLayout.setHorizontalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBawahLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBawahLayout.createSequentialGroup()
                        .addComponent(lblTotal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlBawahLayout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapus)
                        .addGap(18, 18, 18)
                        .addComponent(btnReset)
                        .addGap(18, 18, 18)
                        .addComponent(btnKeluar))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBawahLayout.setVerticalGroup(
            pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBawahLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBawahLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(33, 33, 33))
                    .addGroup(pnlBawahLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(pnlBawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnKeluar)
                    .addComponent(btnSimpan)
                    .addComponent(btnHapus)
                    .addComponent(btnReset))
                .addGap(444, 444, 444))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAtas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlTengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlBawah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTengah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

// === FUNGSI DATABASE ===
    private void loadComboBuku() {
        try (Connection conn = DatabaseConnection.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT id_buku, judul, harga FROM buku")) {
            cmbBuku.removeAllItems();
            mapBuku.clear();
            while (rs.next()) {
                String nama = rs.getString("judul");
                cmbBuku.addItem(nama);
                mapBuku.put(nama, rs.getInt("id_buku"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load buku: " + e.getMessage());
        }
    }

    private void loadComboPelanggan() {
        try (Connection conn = DatabaseConnection.getConnection();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery("SELECT id_pelanggan, nama FROM pelanggan")) {
            cmbPelanggan.removeAllItems();
            mapPelanggan.clear();
            while (rs.next()) {
                String nama = rs.getString("nama");
                cmbPelanggan.addItem(nama);
                mapPelanggan.put(nama, rs.getInt("id_pelanggan"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal load pelanggan: " + e.getMessage());
        }
    }

    private void tambahBuku() {
        try (Connection conn = DatabaseConnection.getConnection()) {
            String judul = (String) cmbBuku.getSelectedItem();
            if (judul == null || txtJumlah.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pilih buku dan masukkan jumlah!");
                return;
            }

            int idBuku = mapBuku.get(judul);
            PreparedStatement pst = conn.prepareStatement("SELECT harga FROM buku WHERE id_buku=?");
            pst.setInt(1, idBuku);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                double harga = rs.getDouble("harga");
                int jumlah = Integer.parseInt(txtJumlah.getText());
                double subtotal = harga * jumlah;
                model.addRow(new Object[]{idBuku, judul, harga, jumlah, subtotal});
                hitungTotal();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal tambah buku: " + e.getMessage());
        }
    }

    private void hapusBaris() {
        int row = tblPenjualan.getSelectedRow();
        if (row >= 0) {
            model.removeRow(row);
            hitungTotal();
        } else {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
        }
    }

    private void resetForm() {
        txtIdPenjualan.setText("");
        txtTanggal.setText("YYYY-MM-DD");
        txtJumlah.setText("");
        txtTotal.setText("");
        model.setRowCount(0);
    }

    private void hitungTotal() {
        double total = 0;
        for (int i = 0; i < model.getRowCount(); i++) {
            total += (double) model.getValueAt(i, 4);
        }
        txtTotal.setText(String.format("%.0f", total));
    }

    private void simpanTransaksi() {
        try (Connection conn = DatabaseConnection.getConnection()) {
            conn.setAutoCommit(false);

            String namaPelanggan = (String) cmbPelanggan.getSelectedItem();
            if (namaPelanggan == null || txtTanggal.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Isi tanggal dan pilih pelanggan!");
                return;
            }

            int idPelanggan = mapPelanggan.get(namaPelanggan);

            String sqlPenjualan = "INSERT INTO penjualan (id_pelanggan, tanggal, total) VALUES (?, ?, ?)";
            PreparedStatement ps = conn.prepareStatement(sqlPenjualan, Statement.RETURN_GENERATED_KEYS);
            ps.setInt(1, idPelanggan);
            ps.setString(2, txtTanggal.getText());
            ps.setDouble(3, Double.parseDouble(txtTotal.getText()));
            ps.executeUpdate();

            ResultSet rs = ps.getGeneratedKeys();
            rs.next();
            int idPenjualan = rs.getInt(1);

            String sqlDetail = "INSERT INTO detail_penjualan (id_penjualan, id_buku, jumlah, subtotal) VALUES (?, ?, ?, ?)";
            PreparedStatement psd = conn.prepareStatement(sqlDetail);

            for (int i = 0; i < model.getRowCount(); i++) {
                psd.setInt(1, idPenjualan);
                psd.setInt(2, Integer.parseInt(model.getValueAt(i, 0).toString()));
                psd.setInt(3, Integer.parseInt(model.getValueAt(i, 3).toString()));
                psd.setDouble(4, Double.parseDouble(model.getValueAt(i, 4).toString()));
                psd.addBatch();
            }
            psd.executeBatch();
            conn.commit();

            JOptionPane.showMessageDialog(this, "Transaksi berhasil disimpan!");
            resetForm();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan transaksi: " + e.getMessage());
        }
    }

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> new PenjualanFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbBuku;
    private javax.swing.JComboBox<String> cmbPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuku;
    private javax.swing.JLabel lblIdPenjualan;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblPelanggan;
    private javax.swing.JLabel lblTanggal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlAtas;
    private javax.swing.JPanel pnlBawah;
    private javax.swing.JPanel pnlTengah;
    private javax.swing.JTable tblPenjualan;
    private javax.swing.JTextField txtIdPenjualan;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
